version: '3.3'
services:
  serverpostgres:
    image: postgres
    container_name: serverpostgres
    hostname: serverpostgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  db8:
    image: mysql:8.0.18
    #restart: always
    environment:
      MYSQL_DATABASE: 'daw'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'daw'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'daw'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
            - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db80:/var/lib/mysql
# Names our volume
volumes:
  my-db80:

