version: "3"
services:

  pcadmin:
    image: busybox
    container_name: pcadmin 
    hostname: pcadmin
    stdin_open: true
    tty: true
    networks:
      - interna

  firewall:
    image: busybox
    container_name: firewall
    hostname: firewall
    stdin_open: true
    tty: true
    networks:
      - interna
      - dmz

  servermysql:
    image: mysql
    container_name: servermysql
    hostname: servermysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - dmz

networks:
  interna:
  dmz:

