version: "3"
services:
  pcadmin:
    image: alpine
    container_name: pcadmin 
    hostname: pcadmin
    stdin_open: true
    tty: true

  vsftpd:
    container_name: vsftpd
    image: wildscamp/vsftpd
    hostname: vsftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - ./docker-html:/home/virtual/www-data/html
      - ./docker-certificates:/home/virtual/certs/certs
      - ./docker-mysql:/home/virtual/mysql/mysql
    environment:
      PASV_ADDRESS: 10.0.75.1
      PASV_MIN_PORT: 30000
      PASV_MAX_PORT: 30009
      VSFTPD_USER_1: 'www-data:ftp:33:'
      VSFTPD_USER_2: 'mysql:mysql:999:'
      VSFTPD_USER_3: 'certs:certs:50:'

